Added option to choose the kmer size and the number of kmers for compareads

diff --git a/NaS_v2/NaS_wrapped b/NaS_v2/NaS_wrapped
--- a/NaS_v2/NaS_wrapped
+++ b/NaS_v2/NaS_wrapped
@@ -56,6 +56,10 @@ function usage(){
     printf "\t--a	       : ONLY in sensitive mode : gap existence cost parameter of last, default is 1\n"
     printf "\t--b	       : ONLY in sensitive mode : gap extension cost parameter of last, default is 1\n"
     printf "\t--e	       : ONLY in sensitive mode : score threshold parameter of last, default is 120\n"
+    printf "\t--t	       : number of substrings for compareads, default is 3\n"
+    printf "\t--k	       : size of substrings for compareads, default is 32\n"
+    printf "\t--k_cookie       : size of substrings for cookiecutter, default is 100\n"
+    printf "\t--untgl_seq_size : minimum size of sequence to run untangle (useful for RNA-Seq), default is 1000\n"
     printf "\t--nb_proc    : Number of parallel task, default is 1\n"
     printf "\t--rmtmp : yes or no : Delete temporary file, default is yes\n" 
     printf "\t-h           : help message\n\n"
@@ -82,6 +86,9 @@ MODE=fast
 A=1
 B=1
 E=40
+T=3
+K=32
+UNTGL_SEQ_SIZE=1000
 TILE=10
 STEP=5
 ILMN_R1=
@@ -145,6 +152,18 @@ while :; do
 		E=$2
 		shift 2
 		;;
+	--t)
+		T=$2
+		shift 2
+		;;
+	--k)
+		K=$2
+		shift 2
+		;;
+	--untgl_seq_size)
+		UNTGL_SEQ_SIZE=$2
+		shift 2
+		;;
 	--rmtmp)
 		RMTMP=$2
 		shift 2
@@ -187,7 +206,7 @@ elif [ "$MODE" == "sensitive" ]; then
 	parallel-fasta -j $NB_PROC --block 10M "lastal -s 2 -T 0 -b $B -e $E -a $A -Q 0 $OUTPUT_DIR/tmp/nanolastdb" < $OUTPUT_DIR/tmp/ILMN_reads.fa > $OUTPUT_DIR/tmp/last-alignment.A$A.B$B.E$E.maf 2>$OUTPUT_DIR/tmp/last-alignment.stderr
 	d=`date`
 	echo "[$d] Convert maf file to psl file..."
-        cat $OUTPUT_DIR/tmp/last-alignment.A$A.B$B.E$E.maf | parallel -j $NB_PROC --cat --pipe --block 10M --recstart "a score=" "maf-convert --noheader psl {} > $OUTPUT_DIR/tmp/psl/last-alignment.A$A.B$B.E$E.job{#}.psl" > $OUTPUT_DIR/tmp/maf-converter.stdout 2> $OUTPUT_DIR/tmp/maf-converter.stderr
+        cat $OUTPUT_DIR/tmp/last-alignment.A$A.B$B.E$E.maf | parallel -j $NB_PROC --cat --pipe --block 100M --recstart "a score=" "maf-convert --noheader psl {} > $OUTPUT_DIR/tmp/psl/last-alignment.A$A.B$B.E$E.job{#}.psl" > $OUTPUT_DIR/tmp/maf-converter.stdout 2> $OUTPUT_DIR/tmp/maf-converter.stderr
 	head -16 $OUTPUT_DIR/tmp/last-alignment.A$A.B$B.E$E.maf > $OUTPUT_DIR/tmp/last-alignment_header.A$A.B$B.E$E.maf
 	rm $OUTPUT_DIR/tmp/last-alignment.A$A.B$B.E$E.maf
 else
@@ -200,7 +219,7 @@ cat $OUTPUT_DIR/tmp/psl/*.psl | awk -v PFX=$OUTPUT_DIR/reads '{ file=PFX"/"$14".
 
 d=`date`
 echo "[$d] Retrieve similar reads..."
-ls -S $OUTPUT_DIR/reads/ | grep psl | sed "s/.psl//" | parallel -j $NB_PROC "selectReads -psl $OUTPUT_DIR/reads/{}.psl -reads $OUTPUT_DIR/tmp/ILMN_inlinereads.fastq -r1 $ILMN_R1 -r2 $ILMN_R2 -size $ILMN_size -prefix $OUTPUT_DIR/tmp/ -name {} -out $OUTPUT_DIR/reads2/{}.fastq >(cat) >&2" > $OUTPUT_DIR/tmp/selectReads.stdout 2>$OUTPUT_DIR/tmp/selectReads.stderr
+ls -S $OUTPUT_DIR/reads/ | grep psl | sed "s/.psl//" | parallel -j $NB_PROC "selectReads -psl $OUTPUT_DIR/reads/{}.psl -reads $OUTPUT_DIR/tmp/ILMN_inlinereads.fastq -r1 $ILMN_R1 -r2 $ILMN_R2 -size $ILMN_size -prefix $OUTPUT_DIR/tmp/ -t $T -k $K -name {} -out $OUTPUT_DIR/reads2/{}.fastq >(cat) >&2" > $OUTPUT_DIR/tmp/selectReads.stdout 2>$OUTPUT_DIR/tmp/selectReads.stderr
 
 d=`date`
 echo "[$d] Generate NaS reads..."
@@ -208,7 +227,7 @@ ls -S $OUTPUT_DIR/reads2/ | sed "s/.fastq//" | parallel --timeout 2000% -j $NB_P
 
 d=`date`
 echo "[$d] Untangle complex NaS reads..."
-ls -S $OUTPUT_DIR/reads2/ | sed "s/.fastq//" | parallel -j $NB_PROC "$UNTANGLE_GRAPH -newblerdir $OUTPUT_DIR/assemblies/{} -nano $OUTPUT_DIR/assemblies/{}/{}.fa -name {} 2>$OUTPUT_DIR/assemblies/{}/stderr_untangle2"
+ls -S $OUTPUT_DIR/reads2/ | sed "s/.fastq//" | parallel -j $NB_PROC "$UNTANGLE_GRAPH -newblerdir $OUTPUT_DIR/assemblies/{} -nano $OUTPUT_DIR/assemblies/{}/{}.fa -minsize $UNTGL_SEQ_SIZE -name {} 2>$OUTPUT_DIR/assemblies/{}/stderr_untangle2"
 cat $OUTPUT_DIR/assemblies/*/NaS_hqctg_reads_final.fa | FastaToTbl | perl -ne '@f=split; $f[1]=~/^([actgn]*)([ACTGN]+[ACTGNactgn]*[ACTGN]+)([actgn]*)$/; if (length ($2)>0){print $f[0], " ", $2, "\n";}' | TblToFasta | sed "s=_contig[0-9]*\$==" > $OUTPUT_DIR/NaS_hqctg_reads.fa
 
 d=`date`
@@ -246,7 +265,7 @@ if [ "$RMTMP" == "yes" ] && [ -s $OUTPUT_DIR/NaS_hqctg_reads.fa ]; then
 	rm $OUTPUT_DIR/assemblies/*/last_ali
 else 
 	d=`date`
-	echo "[$d] Temporary files are not deleted because errors occurs..."
+	echo "[$d] Temporary files were not deleted because errors occured..."
 fi
 
 AFTER=`date +'%s'`
